#!/bin/bash
sudo apt-get purge -y wiringpi
hash -r
sudo apt-get install -y git-core
sudo apt-get update
sudo apt-get upgrade
cd
git clone git://git.drogon.net/wiringPi
cd ~/wiringPi
./build
cd
rm -rf wiringPi
