#!/bin/sh
cd `dirname $0`
sudo ./resize-2gb
./update-system
./enable-hifiberry
./install-autodetect
./enable-spi
./install-tcpserver
./install-dsptoolkit
./install-tools
./cleanup-daemons
./install-players
sudo reboot
