#!/bin/sh
cd `dirname $0`
./update-system
./install-shairport
./install-spotify
mkdir -p /opt/hifiberry/bin
sudo cp write-status /opt/hifiberry/bin
sudo chmod ugo+rx  /opt/hifiberry/bin/write-status

