#!/bin/sh
sudo apt-get install -y sox wiringpi
if [ ! -d "/opt/hifiberry/bin" ]; then
 mkdir -p /opt/hifiberry/bin
fi
for i in write-status detect-hifiberry store-volume; do
 cp $i /opt/hifiberry/bin
done
