#!/bin/sh
sudo apt-get -y install autoconf automake avahi-daemon build-essential git libasound2-dev libavahi-client-dev libconfig-dev libdaemon-dev libpopt-dev libssl-dev libtool xmltoman pkg-config
git clone https://github.com/mikebrady/shairport-sync.git
cd shairport-sync
autoreconf -i -f
./configure --sysconfdir=/etc --with-alsa --with-avahi --with-ssl=openssl --with-systemd --with-metadata
make
sudo make install

# Create shairport configuration
cat <<EOT >/tmp/shairport-sync.conf
general =
{
  name = "BeoCreate"
};

alsa = {
  mixer_control_name = "Master";
};
EOT
sudo mv /tmp/shairport-sync.conf /etc

# Create new systemd file
cat <<EOT >/tmp/shairport-sync.service
[Unit]
Description=Shairport Sync - AirPlay Audio Receiver
After=sound.target
Requires=avahi-daemon.service
After=avahi-daemon.service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/local/bin/shairport-sync -c /etc/shairport-sync.conf
User=shairport-sync
Group=shairport-sync

[Install]
WantedBy=multi-user.target
EOT
sudo mv /tmp/shairport-sync.service /lib/systemd/system/shairport-sync.service

sudo systemctl enable shairport-sync
sudo service shairport-sync start



