#!/bin/sh
sudo apt-get -y install build-essential portaudio19-dev

cd /tmp
wget https://github.com/Spotifyd/spotifyd/releases/download/untagged-49c187b9535b150bb4c7/spotifyd-2018-03-01-armv6.zip
unzip spotifyd-2018-03-01-armv6.zip
rm spotifyd-2018-03-01-armv6.zip
sudo sudo mkdir -p /opt/hifiberry/bin
sudo mv spotifyd /opt/hifiberry/bin

cat <<EOT >spotify.service
[Unit]
Description=Spotify Connect
After=network-online.target
After=sound.target

[Service]
Type=idle
User=pi
ExecStart=/opt/hifiberry/bin/spotifyd -c /etc/spotifyd.conf --no-daemon
Restart=always
RestartSec=10
StartLimitInterval=30
StartLimitBurst=20

[Install]
WantedBy=multi-user.target

EOT

cat <<EOT >spotifyd.conf
[global]
#username = USER
#password = PASS
backend = alsa
mixer = Master
volume-control = alsa # or softvol
device_name = Beocreate
bitrate = 320
onevent = /opt/hifiberry/bin/spotifyd-notification
EOT

sudo cp spotifyd.conf /etc/spotifyd.conf
sudo cp spotify.service /lib/systemd/system/spotify.service
sudo systemctl daemon-reload
sudo systemctl enable spotify.service
sudo systemctl restart spotify.service


