#!/bin/sh
cd `dirname $0`
sudo apt-get install -y i2c-tools
mkdir -p /opt/hifiberry/bin
cp ./detect-hifiberry /opt/hifiberry/bin

# Create new systemd file
cat <<EOT >/tmp/hifiberry-autodetect.service
[Unit]
Description=HiFiBerry sound card automatic detection
After=sound.target

[Service]
Type=oneshot
ExecStart=/opt/hifiberry/bin/detect-hifiberry

[Install]
WantedBy=multi-user.target
EOT
sudo mv /tmp/hifiberry-autodetect.service /lib/systemd/system/hifiberry-autodetect.service

sudo systemctl enable hifiberry-autodetect.service
