#!/bin/bash
curl -s https://raw.githubusercontent.com/lukasjapan/bt-speaker/master/install.sh >/tmp/install-bts
chmod ugo+rx /tmp/install-bts
sudo /tmp/install-bts

cat <<EOF >/tmp/disconnect
#!/bin/bash -x
ogg123 /usr/share/sounds/freedesktop/stereo/service-login.oga
# disconnect wifi to prevent dropouts - TODO: check what permissions bt-speaker might need for this (netdev group?)
sudo ifconfig wlan0 up
/opt/hifiberry/bin/write-status STOP BTSPEAKER
EOF

cat <<EOF >/tmp/connect
#!/bin/bash -x
ogg123 /usr/share/sounds/freedesktop/stereo/service-login.oga
# disconnect wifi to prevent dropouts - TODO: check what permissions bt-speaker might need for this (netdev group?)
sudo ifconfig wlan0 down
/opt/hifiberry/bin/write-status START BTSPEAKER
EOF

cat <<EOF >/tmp/config.ini
[bt_speaker]
play_command = aplay -f cd -
connect_command = /etc/bt_speaker/hooks/connect
disconnect_command = /etc/bt_speaker/hooks/disconnect

[bluez]
device_path = /org/bluez/hci0
discoverable = yes

[alsa]
enabled = yes
mixer = Master
id = 0
cardindex = 0
EOF

sudo cp /tmp/connect /etc/bt_speaker/hooks/connect
sudo cp /tmp/disconnect /etc/bt_speaker/hooks/disconnect
sudo cp /tmp/config.ini /etc/bt_speaker/config.ini
sudo chmod ugo+x /etc/bt_speaker/hooks/connect /etc/bt_speaker/hooks/disconnect

# TODO: change sudo configuration

