#!/bin/bash
# extend size of the root filesystem to 2GB
first_sector=`echo p | fdisk /dev/mmcblk0 | grep Linux| awk '{print $2}'`
cat <<EOF | sudo fdisk /dev/mmcblk0
d
2
n
p
2
$first_sector
+2G
w
EOF
sudo partprobe
sudo resize2fs /dev/mmcblk0p2
